### PR TITLE
Add support for dynamically growing content

### LINKED ISSUE #44: scroll-affix breaks when the affix dynamically grows
if you scroll-affix something that is smaller height than viewport (no scroll needed), scroll down slightly, and then dynamically grow it such that it becomes taller than the viewport, you won't be able to get the affix to scroll until you reach the top or bottom of the main content.

To see issue, use this:
https://jsfiddle.net/dhab1z3e/1/

Scroll down a little, then click the "SHOW MORE BUTTON", then continue scrolling. Note that the affix does not scroll.

It works correctly if you SHOW MORE before scrolling, or return back to the top so that the affix position resets to normal and then begin scrolling again.

### PR DESCRIPTION
**Pull request by Stormtv**
Hi this fixes https://github.com/eddiemf/vue-affix/issues/44

You still are required to call the onScroll function when the content is changed. I also think it might be worth looking into changing the onScroll function to something like refresh but I didn't want to over impose.

I also set the CSS style to scoped.

Thanks!

### CODE REVIEW

**Comment by Stormtv** [comment]
@eddiemf Is this PR sufficient to fix the issue described in #44?

Edit: found an edge case that isn't supported in the PR, I'll have a fix to fix it soon.

**Comment by eddiemf** [comment]
Hey @Stormtv, sorry for the delay, I currently don't have a lot of free time to maintain my repos, but I'll recap everything related to them this weekend and check if everything is cool, thanks a lot for the help :)

**Comment by Stormtv** [comment]
No problem I’m still touching things up. I think there is one small edge case that isn’t perfect. I’ll make a list of any bugs I can find or try to fix them.

**Comment by Stormtv** [comment]
Closing this for now, hopefully I will find time to come back and finish the small bugs but I haven't had an opportunity to work on it. If anyone is looking into this in the future it might be a good starting point. The version here works for my use cases but there are outliers in the implementations that would be buggy in certain contexts.

**Pull request closed without merging**
